### ISSUE TITLE
ecobee server sends unexpected response

### ISSUE THREAD

**Issue by rtwfroody** [rtwfroody/quick_home_away#1]
Sometimes you get a stacktrace like this:

```
Traceback (most recent call last):
  File "quick_home_away.py", line 290, in main
    app.aggressiveAway()
  File "quick_home_away.py", line 180, in aggressiveAway
    updated = self.poll()
  File "quick_home_away.py", line 169, in poll
    for revision in summary[ 'revisionList' ]:
KeyError: 'revisionList'
```

Presumably the server sends us something that we don't expect. I should change the code to print out the actual output in this case, and go from there.

**Comment by rtwfroody** [comment]
Fixed in change 55492bd77847ba456fffbbb73499d72c83148ad0
